- name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

- name: Ensure Nginx is running
    ansible.builtin.service:
      name: nginx
      state: started
    
- name: Configure Nginx with HTTPS #80 was previously 443, för HTTP 80, för HTTPS 443
  copy:
    dest: /etc/nginx/sites-enabled/default
    content: |
        server {
          listen 443 ssl;
          server_name webserver.lab.local;

           ssl_certificate     /opt/ca/certificate.pem;
           ssl_certificate_key /opt/ca/webserver.key;

           location / {
            add_header Content-Type text/plain;
            return 200 'Hello from webserver.lab.local over HTTPS!\n';
          }
        }

    notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted