
# Deklarering av variabler
CA_IP = "10.0.0.1"
WEBSERVER_IP = "10.0.0.2"

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	# VM 1: Certificate Authority
	config.vm.define "ca" do |ca|
		ca.vm.hostname = "ca"
		ca.vm.network "private_network", ip: CA_IP
		ca.vm.provider "virtualbox" do |vb|
			vb.name = "ca"
			vb.memory = 512
			vb.cpus = 1
		end #Avslutar VB-konf

		ca.vm.provision "shell", inline: <<-SHELL
      		apt-get update -y
      		apt-get install -y ansible

      # Generera SSH-nyckelpar som vagrant-användaren.
      # -N "" = inget lösenordsskydd på nyckeln.
      		sudo -u vagrant ssh-keygen -t ed25519 \
        		-f /home/vagrant/.ssh/id_ed25519 \
        		-N "" -C "ansible-kontroll"

      # /vagrant/ är Vagrants delade mapp.
      # Filer här syns av alla VMs och av Windows-hosten.
      		cp /home/vagrant/.ssh/id_ed25519.pub \
         	/vagrant/ansible_id_ed25519.pub

      		echo "=== CA klar ==="
    	SHELL
	end #Avslutar VM1

# VM 2: Webserver
	config.vm.define "webserver" do |web|
		web.vm.hostname = "webserver"
		web.vm.network "private_network", ip: WEBSERVER_IP
		web.vm.provider "virtualbox" do |vb|
			vb.name = "webserver"
			vb.memory = 512
			vb.cpus = 1
        end #Avslutar VB-konf

		web.vm.provision "shell", inline: <<-SHELL
      		apt-get update -y
      		apt-get install -y ansible

      # Generera SSH-nyckelpar som vagrant-användaren.
      # -N "" = inget lösenordsskydd på nyckeln.
      # I produktion SKA nyckeln ha ett lösenord (passphrase).
      # I labbmiljö skippar vi det för enkelhets skull.
      		sudo -u vagrant ssh-keygen -t ed25519 \
        		-f /home/vagrant/.ssh/id_ed25519 \
        		-N "" -C "ansible-kontroll"

      # /vagrant/ är Vagrants delade mapp.
      # Filer här syns av alla VMs och av Windows-hosten.
      		cp /home/vagrant/.ssh/id_ed25519.pub \
         	/vagrant/ansible_id_ed25519.pub

      		echo "=== Ansible-kontroll klar ==="
    	SHELL
	end #Avslutar vm2


end #Avslutar hela Vagrant

	