
# Variables
CA_IP = "10.0.0.1"
WEBSERVER_IP = "10.0.0.2"

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	# VM 1: Certificate Authority
	config.vm.define "ca" do |ca|
		ca.vm.hostname = "ca"
		ca.vm.network "private_network", ip: CA_IP
		ca.vm.provider "virtualbox" do |vb|
			vb.name = "ca"
			vb.memory = 512
			vb.cpus = 1
		end #ends VB-conf

		ca.vm.provision "shell", inline: <<-SHELL
      		apt-get update -y
      		apt-get install -y ansible

      	# Generate SSH keys 
      		sudo -u vagrant ssh-keygen -t ed25519 \
        		-f /home/vagrant/.ssh/id_ed25519 \
        		-N "" -C "ansible-kontroll" 

      	# Copy public key to shared folder
      		cp /home/vagrant/.ssh/id_ed25519.pub \
         	/vagrant/ansible_id_ed25519.pub

      		echo "=== CA done ==="
    	SHELL
	end #End VM1

	# VM 2: Webserver
	config.vm.define "webserver" do |web|
		web.vm.hostname = "webserver"
		web.vm.network "private_network", ip: WEBSERVER_IP
		web.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true #onödig med nuvarande konf om vi ansluter via https://10.0.0.2
		web.vm.provider "virtualbox" do |vb|
			vb.name = "webserver"
			vb.memory = 512
			vb.cpus = 1
        end #End VB-conf

		# Make sure that VM1's public keye is generated
		web.vm.provision "shell", inline: <<-SHELL		
		 	while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
        		sleep 3
      		done

			# Create folders and copy over public key from VM1
		    mkdir -p /home/vagrant/.ssh
      		cat /vagrant/ansible_id_ed25519.pub \
        		>> /home/vagrant/.ssh/authorized_keys
      		chmod 700 /home/vagrant/.ssh
      		chmod 600 /home/vagrant/.ssh/authorized_keys
      		chown -R vagrant:vagrant /home/vagrant/.ssh
      
			echo "=== Webserver done ==="
    	SHELL
	end #End VM2


end #End all
	