- name: Create directory on Webserver
  file:
    path: /opt/ca
    state: directory
    mode: '0755'

- name: Generate Webserver-key #(RSA 4096 bits)
  community.crypto.openssl_privatekey:
    path: /opt/ca/webserver.key

- name: Create certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: /opt/ca/webserver.key
    common_name: webserver.lab.local
    subject_alt_name:
      - "DNS:webserver.lab.local"
      - "IP:{{ ansible_host }}"   # dynamic, not hardcoded
  register: csr

- name: Write CSR to file
  copy:
    dest: /opt/ca/webserver.csr
    content: "{{ csr.csr }}"
    mode: '0644'