---
- name: Fetch CSR from webserver
  fetch:
    src: /opt/ca/webserver.csr
    dest: /tmp/{{ item }}_webserver.csr
    flat: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['webserver'] }}"

- name: Copy CSR to CA
  copy:
    src: /tmp/{{ item }}_webserver.csr
    dest: /opt/ca/{{ item }}_webserver.csr
    mode: '0644'
  loop: "{{ groups['webserver'] }}"

- name: Check whether certificate exists
  stat:
    path: /opt/ca/{{ item }}_certificate.crt
  register: certificate_exists
  loop: "{{ groups['webserver'] }}"

- name: Read existing certificate if exists
  slurp:
    src: /opt/ca/{{ item }}_certificate.crt
  when: certificate_exists.results[loop_index].stat.exists
  loop: "{{ groups['webserver'] }}"
  loop_control:
    index_var: loop_index
  register: certificate

- name: Sign certificate with our CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ lookup('file', '/opt/ca/' + item + '_webserver.csr') }}"
    provider: ownca
    ownca_path: /opt/ca/ca.crt
    ownca_privatekey_path: /opt/ca/ca.key
    ownca_not_after: +365d
    ownca_not_before: "-1d"
  loop: "{{ groups['webserver'] }}"
  register: certificates

- name: Write certificate file on webserver
  copy:
    dest: /opt/ca/certificate.crt
    content: "{{ certificates.results[loop_index].certificate }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['webserver'] }}"
  loop_control:
    index_var: loop_index
  #when: certificate is changed