- name: Installera openssl
  hosts: ca
  become: yes
  tasks:
    
    - name: install Open SSL 
      ansible.builtin.apt:
        name: openssl
        state: present

    - name: skapa CA-mapp
      file:
        path: /opt/ca
        state: directory
        mode: '0700'

    - name: generera CA-nyckel
      command: >
        openssl genrsa -out /opt/ca/ca.key 4096
      args:
        creates: /opt/ca/ca.key

    - name: Generera CA-certifikat (självsignerat, 10 år)
      command: >
        openssl req -new -x509 -days 3650
        -key /opt/ca/ca.key
        -out /opt/ca/ca.crt
        -subj "/CN=Lab Internal CA/O=Lab/C=SE"
      args:
        creates: /opt/ca/ca.crt

    #- name: Signera webbserverns certifikat med CA
    #  command: >
    #    openssl x509 -req -days 365
    #    -in /opt/ca/webserver.csr
    #    -CA /opt/ca/ca.crt
    #    -CAkey /opt/ca/ca.key
    #    -CAcreateserial
    #    -out /opt/ca/webserver.crt
    #  args:
    #    creates: /opt/ca/webserver.crt

    #- name: Hämta CA-cert och webbserver-cert/nyckel som facts
    #  fetch:
    #    src: "{{ item }}"
    #    dest: "ansible/files/"
    #    flat: yes
    #  loop:
    #    - /opt/ca/ca.crt
    #    - /opt/ca/webserver.crt
    #    - /opt/ca/webserver.key