- name: Installera openssl
  hosts: localhost
  become: yes
  tasks:
    
    - name: install Open SSL 
      apt:
        name: openssl
        state: present

    - name: skapa CA-mapp
      file:
        path: /opt/ca
        state: directory
        mode: '0700'

    - name: generera CA-nyckel
      command: >
        openssl genrsa -out /opt/ca/ca.key 4096
      args:
        creates: /opt/ca/ca.key