---
- name: Install Open SSL
  ansible.builtin.apt:
    name: openssl
    state: present
    update_cache: yes

- name: Create directory on CA
  file:
    path: /opt/ca
    state: directory
    mode: '0755'

- name: Generate CA-key #(RSA 4096 bits)
  community.crypto.openssl_privatekey:
    path: /opt/ca/ca.key
  run_once: true


- name: Generate CA CSR 
  community.crypto.openssl_csr_pipe:
    privatekey_path: /opt/ca/ca.key
    common_name: Lab Internal CA
    organization_name: Lab
    country_name: SE
  register: ca_csr 

- name: Create simple self-signed certificate  
  community.crypto.x509_certificate:    
    path: /opt/ca/ca.crt    
    privatekey_path: /opt/ca/ca.key
    csr_content: "{{ ca_csr.csr }}"   
    provider: selfsigned  

