- name: Configure Certificates
  hosts: localhost
  become: yes
  tasks:

  - name: Install Open SSL
    ansible.builtin.apt:
      name: openssl
      state: present
      update_cache: yes

  - name: Create directory on CA
    file:
      path: /opt/ca
      state: directory
      mode: '0755'
  
  - name: Create directory on Webserver
    file:
      path: /opt/ca
      state: directory
      mode: '0755'
    delegate_to: "{{ groups['webserver'][0] }}"

  - name: Generate CA-key #(RSA 4096 bits)
    community.crypto.openssl_privatekey:
      path: /opt/ca/ca.key
    run_once: true

  - name: Generate CA CSR
    community.crypto.openssl_csr_pipe:
      privatekey_path: /opt/ca/ca.key
      common_name: Lab Internal CA
      organization_name: Lab
      country_name: SE
    register: ca_csr

  - name: Create simple self-signed certificate  
    community.crypto.x509_certificate:    
      path: /opt/ca/ca.crt    
      privatekey_path: /opt/ca/ca.key
      csr_content: "{{ ca_csr.csr }}"   
      provider: selfsigned

  - name: Generate Webserver-key #(RSA 4096 bits)
    community.crypto.openssl_privatekey:
      path: /opt/ca/webserver.key
    delegate_to: "{{ groups['webserver'][0] }}"
    run_once: true
 
  - name: Create certificate signing request (CSR) for new certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: /opt/ca/webserver.key
      common_name: webserver.lab.local
      subject_alt_name:
        - "DNS:webserver.lab.local"
        - "IP:10.0.0.2"
    delegate_to: "{{ groups['webserver'][0] }}"
    run_once: true
    register: csr

  - name: Check whether certificate exists
    stat:
      path: /opt/ca/certificate.pem
    delegate_to: "{{ groups['webserver'][0] }}"
    run_once: true
    register: certificate_exists

  - name: Read existing certificate if exists
    slurp:
      src: /opt/ca/certificate.pem
    when: certificate_exists.stat.exists
    delegate_to: "{{ groups['webserver'][0] }}"
    run_once: true
    register: certificate

  - name: Sign certificate with our CA
    community.crypto.x509_certificate_pipe:
      content: "{{ (certificate.content | b64decode) if certificate_exists.stat.exists else omit }}"
      csr_content: "{{ csr.csr }}"
      provider: ownca
      ownca_path: /opt/ca/ca.crt
      ownca_privatekey_path: /opt/ca/ca.key
      ownca_not_after: +365d  # valid for one year
      ownca_not_before: "-1d"  # valid since yesterday
    run_once: true
    register: certificate

  - name: Write certificate file on webserver
    copy:
      dest: /opt/ca/certificate.pem
      content: "{{ certificate.certificate }}"
    delegate_to: "{{ groups['webserver'][0] }}"
    run_once: true
    when: certificate is changed