---
- name: Configure Certificates
  hosts: ca
  become: yes
  roles:
    - CA-config

- name: Create certificate and CSR
  hosts: webserver
  become: yes
  roles:
    - WS-CSR
    
- name: Sign CSR request
  hosts: ca
  become: yes
  roles:
    - CA-sign

- name: Install and configure nginx
  hosts: webserver
  become: yes
  roles:
    - nginx