---
- name: Configure Certificates
  hosts: localhost
  become: yes
  roles:
    - config

- name: Create certificate and CSR
  hosts: webserver
  become: yes
  roles:
    - csr
    
- name: Sign CSR request
  hosts: localhost
  become: yes
  roles:
    - sign

- name: Install and configure nginx
  hosts: webserver
  become: yes
  roles:
    - nginx